services:
  app:
    image: mlopsclassif  # Replace with your image name
    ports:
      - "8000:8000"  # Map port 8000 on host to port 8000 on the container
    environment:
      DATABASE_URL: "postgresql://postgres:123@db:5432/postgres"  # Adjusted to refer to 'db' service in Docker network
    volumes:
      - .:/app  # Optional: mount current directory to /app in container
    depends_on:
      - db  # Ensure the db service is started before the app

  db:
    image: postgres:latest  # Specify your DB image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Map PostgreSQL port

networks:
  default:
    driver: bridge  # Use the default bridge network

